# Generated by Django 5.2.1 on 2025-05-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='bot_response',
            new_name='response',
        ),
    ]
